# Generated by Django 5.0.6 on 2024-05-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(max_length=15)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Bishkek', 'Bishkek'), ('Chuy', 'Chuy'), ('Osh', 'Osh'), ('Naryn', 'Naryn'), ('Talas', 'Talas'), ('Issyk Kul', 'Issyk Kul'), ('Jalal Abad', 'Jalal Abad'), ('Batken', 'Batken')], max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
