# Generated by Django 5.0.6 on 2024-06-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_remove_university_faculty_university_faculties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='category',
            new_name='region',
        ),
    ]
