# Generated by Django 5.0.6 on 2024-06-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_rename_category_university_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='region',
            new_name='category',
        ),
    ]
